In [68]:
import pandas as pd 
import numpy as np

In [69]:
df = pd.read_csv('dirty_cafe_sales.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

In [71]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
9995    False
9996    False
9997    False
9998    False
9999    False
Length: 10000, dtype: bool

In [72]:
missing_valuesSum = df.isnull().sum

In [126]:
#replace all null known values as nan
junk_values = ['UNKNOWN', 'Unknown', 'unknown', 'ERROR', 'Error', 'error', '<NA>', 'na', 'inf', np.inf, 'NaN']
df = df.replace(junk_values, np.nan)
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,4.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,12.0,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,4.0,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,10.0,5.0,10.0,Cash,Takeaway,2023-04-27
4,TXN_3160411,Coffee,4.0,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9993,TXN_4766549,Smoothie,8.0,4.0,8.0,Cash,Takeaway,2023-10-20
9995,TXN_7672686,Coffee,4.0,2.0,4.0,Cash,Takeaway,2023-08-30
9997,TXN_5255387,Coffee,8.0,2.0,8.0,Digital Wallet,Takeaway,2023-03-02
9998,TXN_7695629,Cookie,3.0,1.0,3.0,Digital Wallet,Takeaway,2023-12-02
9999,TXN_6170729,Sandwich,12.0,4.0,12.0,Cash,In-store,2023-11-07

In [128]:
#replace str objects to int
df['Quantity'] = df['Quantity'].astype('Float64')
df['Price Per Unit'] = df['Price Per Unit'].astype('Float64')
df['Total Spent'] = df['Total Spent'].astype('Float64')

In [129]:
df= df.dropna(subset = ['Item'])
df = df.replace('', 0)

In [130]:
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,4.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,12.0,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,4.0,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,10.0,5.0,10.0,Cash,Takeaway,2023-04-27
4,TXN_3160411,Coffee,4.0,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9993,TXN_4766549,Smoothie,8.0,4.0,8.0,Cash,Takeaway,2023-10-20
9995,TXN_7672686,Coffee,4.0,2.0,4.0,Cash,Takeaway,2023-08-30
9997,TXN_5255387,Coffee,8.0,2.0,8.0,Digital Wallet,Takeaway,2023-03-02
9998,TXN_7695629,Cookie,3.0,1.0,3.0,Digital Wallet,Takeaway,2023-12-02
9999,TXN_6170729,Sandwich,12.0,4.0,12.0,Cash,In-store,2023-11-07

In [141]:
df['Total Spent'] = df['Total Spent'].fillna(0)
df['Quantity'] = df['Quantity'].fillna(0)
df['Price Per Unit'] = df['Price Per Unit'].fillna(0)

In [142]:
df['Total Spent'] = np.where(df['Total Spent'] == 0, df['Quantity'] * df['Price Per Unit'], 
                             df['Total Spent'])
df['Quantity'] = np.where(df['Quantity'] == 0, df['Total Spent'] / df['Price Per Unit'].replace(0, 1), 
                             df['Total Spent'])

df['Price Per Unit'] = np.where(df['Price Per Unit'] == 0, df['Total Spent'] / df['Quantity'].replace(0, 1), df['Price Per Unit'])

In [143]:
df['Payment Method'] = np.where(
    (df['Payment Method'].isna()) & (df['Location'] == 'Online'), 
    'Credit Card', 
    df['Payment Method']
)

In [144]:
df['Payment Method'] = df['Payment Method'].fillna('Cash')

In [145]:
most_common_store = df['Location'].mode()[0]
df['Location'] = df['Location'].fillna(most_common_store)

Transaction ID        0
Item                  0
Quantity              0
Price Per Unit        0
Total Spent           0
Payment Method        0
Location              0
Transaction Date    418
dtype: int64

In [151]:
df = df.dropna(subset=['Transaction Date'])

In [155]:
df = df.sort_values(by="Transaction Date", ascending = True)

In [157]:

df['Transaction Date'] = df['Transaction Date'].ffill()

In [158]:
df.isnull().sum()

Transaction ID      0
Item                0
Quantity            0
Price Per Unit      0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
dtype: int64

In [159]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8613 entries, 7306 to 2618
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    8613 non-null   object
 1   Item              8613 non-null   object
 2   Quantity          8613 non-null   float64
 3   Price Per Unit    8613 non-null   float64
 4   Total Spent       8613 non-null   float64
 5   Payment Method    8613 non-null   object
 6   Location          8613 non-null   object
 7   Transaction Date  8613 non-null   object
dtypes: float64(3), object(5)
memory usage: 605.6+ KB

In [163]:
df.to_csv('cleaned_cafe_sales.csv', index=False)

0